Spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/Corder
    username: postgres
    password: Morrigan551!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: create
    show-sql: true
    database: postgresql
    properties:
        hibernate:
          format_sql: true