Spring:
  datasource:
    url:  jdbc:postgresql://192.168.200.103:5432/corder
    username: postgres
    password: Cloud@2023
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 16f4841f49d2f9
    password: 570e8bf1b9ab8a
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080